name: "ROS Semantic Release Action"
description: "Uses semantic release to build and release ros packages as debians"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  ros2_distro:
    description: "The version of ros2 to build for (eg galactic or humble). The version of ros_builder must be correct!"
    default: "galactic"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Copy some assets into the repo root
      shell: bash
      run: cp ${GITHUB_ACTION_PATH}/package.json ${GITHUB_ACTION_PATH}/yarn.lock .

    - name: NPM install
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Chown
      shell: bash
      run: chown -R $(whoami) .

    - name: Install platform_cli
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        pip install https://github.com/Greenroom-Robotics/platform_cli/archive/refs/heads/feature/pkg-cmds.zip

    - name: Setup rosdep and apt lists
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      run: platform pkg setup

    - name: Install rosdep deps
      shell: bash
      env:
        GHCR_PAT: ${{ inputs.token }}
      run: platform pkg install-deps
    
    - name: Generate package.jsons
      shell: bash
      env:
         PACKAGES_DIRECTORY: packages
      run: python3 ${GITHUB_ACTION_PATH}/scripts/generate-package-jsons.py

    - name: Semantic Release
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        ROS2_DISTRO: ${{ inputs.ros2_distro }}
      run: yarn release
