name: "ROS Semantic Release Action"
description: "Uses semantic release to build and release ros packages as debians"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  changelog:
    description: "Should we generate and commit back a changelog?"
    default: "true"
  github_release:
    description: "Should we create a github release?"
    default: "true"
  skip_tag:
    description: "Should we skip creating a git tag?"
    default: "false"
  skip_build:
    description: "Should we skip building the packages?"
    default: "false"
  public:
    description: "Should the packages be public?"
    default: "false"
  package:
    description: "The package to release. If not set, all packages in the 'package_dir' will be released."
    default: ""
  package_dir:
    description: "The directory to release packages from. If not set, the root of the repo will be used."
    default: "./"
  arch:
    description: "The architecture to build for (eg amd64 or arm64)."
    default: "amd64"
  ros_distro:
    description: "The version of ros2 to build for (eg galactic or humble). This will be passed into the Dockerfile as $ROS_DISTRO."
    default: "iron"
  release_branches:
    description: "The branches to release from. Comma separated list."
    default: "main,master,alpha"
  cli_branch:
    description: "The branch of platform_cli to use"
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Collect Workflow Telemetry
      uses: Greenroom-Robotics/workflow-telemetry-action@main

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Setup Poetry
      shell: bash
      run: sudo pip install poetry-plugin-export

    - name: Install platform_cli
      shell: bash
      run: pip install git+https://github.com/Greenroom-Robotics/platform_cli.git@${{ inputs.cli_branch }}

    - name: Setup Release Environment
      shell: bash
      run: |
        platform release setup \
        --package=${{ inputs.package }} \
        --package-dir=${{ inputs.package_dir }}

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      if: ${{ inputs.skip_build == 'true' }}
      with:
        pattern: build-*
        path: ${{ inputs.package_dir }}
        merge-multiple: true

    - name: Create Release
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_USER: ${{ github.actor }}
      shell: bash
      run: |
        platform release create \
        --changelog=${{ inputs.changelog }} \
        --public=${{ inputs.public }} \
        --package=${{ inputs.package }} \
        --package-dir=${{ inputs.package_dir }} \
        --arch=${{ inputs.arch }} \
        --ros-distro=${{ inputs.ros_distro }} \
        --github-release=${{ inputs.github_release }} \
        --skip-tag=${{ inputs.skip_tag }} \
        --skip-build=${{ inputs.skip_build }} \
        --branches=${{ inputs.release_branches }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ inputs.skip_build == 'false' }}
      with:
        name: build-${{ inputs.arch }}-${{ inputs.ros_distro }}
        path: |
          ${{ inputs.package_dir }}/debs/*.deb
          ${{ inputs.package_dir }}/debs/*.ddeb
          ${{ inputs.package_dir }}/*/debs/*.deb
          ${{ inputs.package_dir }}/*/debs/*.ddeb
        compression-level: 0 # no compression
