name: "ROS Semantic Release Action"
description: "Uses semantic release to build and release ros packages as debians"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  ros2_distro:
    description: "The version of ros2 to build for (eg galactic or humble). The version of ros_builder must be correct!"
    default: "galactic"
    deprecated: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install platform_cli
      shell: bash
      run: pip install git+https://github.com/Greenroom-Robotics/platform_cli.git@main

    - name: Platform Release Setup
      shell: bash
      run: platform release setup

    - name: Platform Release Create
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: platform release create