name: "ROS Semantic Release Action"
description: "Uses semantic release to build and release ros packages as debians"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  changelog:
    description: "Should we generate and commit back a changelog?"
    default: "true"
  github_release:
    description: "Should we create a github release?"
    default: "true"
  skip_tag:
    description: "Should we skip creating a git tag?"
    default: "false"
  skip_build:
    description: "Should we skip building the packages?"
    default: "false"
  public:
    description: "Should the packages be public?"
    default: "false"
  package:
    description: "The package to release. If not set, all packages in the 'package_dir' will be released."
    default: ""
  package_dir:
    description: "The directory to release packages from. If not set, the root of the repo will be used."
    default: "./"
  arch:
    description: "The architecture to build for (eg amd64 or arm64)."
    default: "amd64"
  ros_distro:
    description: "The version of ros2 to build for (eg galactic or humble). This will be passed into the Dockerfile as $ROS_DISTRO."
    default: "iron"

runs:
  using: "composite"
  steps:
    - name: Collect Workflow Telemetry
      uses: Greenroom-Robotics/workflow-telemetry-action@main

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Setup Python
      shell: bash
      run: |
        # We are not using the @actions/setup-python action because it does not work on arm64
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        curl -sSL https://install.python-poetry.org | python3
        sudo pip install poetry-plugin-export

    - name: Install platform_cli
      shell: bash
      run: pip install git+https://github.com/Greenroom-Robotics/platform_cli.git@feature/tag-post-build

    - name: Platform Release Setup
      shell: bash
      run: |
        platform release setup \
        --package=${{ inputs.package }} \
        --package-dir=${{ inputs.package_dir }}

    - name: Platform Release Create
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_USER: ${{ github.actor }}
      shell: bash
      run: |
        platform release create \
        --changelog=${{ inputs.changelog }} \
        --public=${{ inputs.public }} \
        --package=${{ inputs.package }} \
        --package-dir=${{ inputs.package_dir }} \
        --arch=${{ inputs.arch }} \
        --ros-distro=${{ inputs.ros_distro }} \
        --github-release=${{ inputs.github_release }} \
        --skip-tag=${{ inputs.skip_tag }} \
        --skip-build=${{ inputs.skip_build }}
