name: "ROS Semantic Release Action"
description: "Uses semantic release to build and release ros packages as debians"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  packages_directory:
    description: "The directory in which ros packages are located"
    required: false
    default: packages

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2

    # - name: Load cached poetry
    #   id: cached-poetry-dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cache/pypoetry
    #     key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install poetry
      shell: bash
      run: |
        pip install poetry
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry config virtualenvs.create false

    - name: Copy some assets into the repo root
      shell: bash
      run: cp ${GITHUB_ACTION_PATH}/package.json ${GITHUB_ACTION_PATH}/yarn.lock .

    - name: NPM install
      shell: bash
      run: yarn install --frozen-lockfile

    # - name: Poetry Install
    #   shell: bash
    #   if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    #   run: python3 ${GITHUB_ACTION_PATH}/scripts/poetry-install.py

    - name: Chown
      shell: bash
      run: chown -R $(whoami) .

    - name: ROS Setup
      shell: bash
      env:
        ROSDISTRO_OVERLAY_INDEX_URL: https://raw.githubusercontent.com/Greenroom-Robotics/rosdistro/main/overlay.yaml
        ROS2_DISTRO: galactic
        GHCR_PAT: ${{ inputs.token }}
        API_TOKEN_GITHUB: ${{ inputs.token }}
        PACKAGES_DIRECTORY: ${{ inputs.package_directory }}
      run: bash ${GITHUB_ACTION_PATH}/scripts/ros-setup.sh

    - name: Colcon build
      shell: bash
      env:
        ROS2_DISTRO: galactic
        PACKAGES_DIRECTORY: ${{ inputs.package_directory }}
      run: bash ${GITHUB_ACTION_PATH}/scripts/ros-build.sh

    - name: Generate package.jsons
      shell: bash
      env:
        PACKAGES_DIRECTORY: ${{ inputs.package_directory }}
      run: python3 ${GITHUB_ACTION_PATH}/scripts/generate-package-jsons.py

    - name: Semantic Release
      shell: bash
      env:
        DEB_OUTPUT_DIRECTORY: "./deb-output"
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.token }}
        API_TOKEN_GITHUB: ${{ inputs.token }}
        ROS2_DISTRO: galactic
        PUBLISH_SOURCE_FILE: "./deb-output/*.deb"
        PUBLISH_DESTINATION_REPO: "Greenroom-Robotics/packages"
        PUBLISH_DESTINATION_FOLDER: "debian"
        PUBLISH_USER_NAME: "ci@greenroomrobotics.com"
        PUBLISH_USER_EMAIL: "Github CI"
      run: yarn release
